// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eulbeetmncbrnrzstfbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1bGJlZXRtbmNicm5yenN0ZmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDY1MTgsImV4cCI6MjA2NDAyMjUxOH0.OFiGN3YGRlOvYNCExuDXXGMW4MR1_rV8MfPWAEZ3lk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);